import { Type } from '@openmrs/esm-framework';

/**
 * The reportingrest REST API serialises each result row as a JSON object whose
 * key order is not guaranteed to match the SQL SELECT order, so the columns can
 * come out alphabetical. For the reports listed in `columnOrderByUuid` we render
 * columns in the configured fixed order (matching the source paper layout); any
 * columns present in the data but not listed are appended afterwards.
 *
 * `hiddenDatasets` lists dataset names that exist only to feed an Excel template
 * and should not be shown in the on-screen table.
 *
 * Both are exposed through the O3 config system so the order can be tuned per
 * implementation without rebuilding the frontend.
 */
export const configSchema = {
  columnOrderByUuid: {
    _type: Type.Object,
    _description:
      'Map of report definition UUID -> ordered array of column names. Columns are rendered in this order; unlisted columns are appended.',
    _default: {
      'c7e1d4a8-3f2b-4c6e-9a51-2d8f7b0e4a93': [
        'S.N',
        'Infant MRN',
        'Name of infant',
        'Date of Birth (DD/MM/YY)',
        'Sex (M/F)',
        'Name of mother',
        'Mother MRN',
        'Woreda',
        'Kebele',
        'Gott',
        'House Number',
        'Reg. Date (DD/MM/YY)',
        'BCG (DD/MM/YY)',
        'OPV 0',
        'OPV 1',
        'OPV 2',
        'OPV 3',
        'Hep Birth dose within 24 hrs',
        'Hep Birth dose after 24 hrs',
        'DPT-HepB-Hib 1 (DD/MM/YY)',
        'DPT-HepB-Hib 2 (DD/MM/YY)',
        'DPT-HepB-Hib 3 (DD/MM/YY)',
        'PCV 1 (DD/MM/YY)',
        'PCV 2 (DD/MM/YY)',
        'PCV 3 (DD/MM/YY)',
        'Rota 1 (DD/MM/YY)',
        'Rota 2 (DD/MM/YY)',
        'IPV (DD/MM/YY)',
        'Measles 1 (DD/MM/YY)',
        'Measles 2 (DD/MM/YY)',
        'Fully immunized (V)',
        'No. of Td doses Mother received in last pregnancy',
        'Total No. of Td doses birth Mother received',
        'Protected at Birth (PAB) (V)',
        'Nutritional screening date (DD/MM/YY)',
        'Screened & linked to CINuS (V)',
        'Developmental milestones',
        'Remark/Appointment',
      ],
      'e1ad4e03-8522-4262-9330-b646274d08ae': [
        'S.N',
        'Name/Kebele',
        'MRN',
        'Age',
        'LNMP (DD/MM/YY)',
        'EDD (DD/MM/YY)',
        'Contact Number',
        'Date of Contact (DD/MM/YY)',
        'Gestational Age in weeks (GA)',
        'Ultrasound performed within 24 Weeks of GA',
        'Syphilis test result (R/NR/ND)',
        'Syphilis Treatment Given',
        'Hepatitis B test result (R/NR/ND)',
        'Hepatitis B Treatment Given',
        'Hepatitis B prophylaxis given',
        'Td provided (dose number)',
        'IFA/Ferrous sulphate with folic acid (Tabs)',
        'Deworming provided',
        'MUAC (cm)',
        'HIV Test accepted',
        'HIV test result (P/N)',
        'Targeted population category',
        'HIV results received with post test counseling',
        'HIV Positive Linked to PMTCT',
        'Known HIV positives (transferred from ART)',
        'Partner HIV Test accepted',
        'Partner HIV Test result (P/N)',
        'Partner Targeted population category',
        'HIV Positive partner Linked to ART',
        'Counseled on Danger Signs',
        'Counseled on Maternal Nutrition',
        'Counseled on Early Childhood Development',
        'Counseled on infant feeding',
        'Counseled on family planning',
        'Remark/Appointment/Action',
      ],
      '6cb350d7-afa0-4ad7-94b5-990f6450c610': [
        'S.N',
        'Date (DD/MM/YY)',
        'MRN',
        'Age',
        'Gestational age (wks)',
        'Gravida',
        'Para',
        'No. of previous abortions',
        'Safe abortion care (√)',
        'Post abortion care (√)',
        'Diagnosis/ Reason for safe/post abortion care',
        'MVA (√)',
        'E&C (√)',
        'MA (√)',
        'D&E (√)',
        'Other (specify)',
        'Out-patient (√)',
        'In-patient (√)',
        'Referred (√)',
        'Drugs provided / Dose given',
        'Counseled (√)',
        'Expressed desire (√)',
        'New acceptor (√)',
        'Repeat acceptor (√)',
        'Contraceptive Method/s Provided',
        'HIV test accepted (√)',
        'Target population Category',
        'HIV test result (P/N)',
        'HIV test received with post test counseling (√)',
        'HIV positives linked to ART (√)',
        'Complications (if yes specify or No)',
        'Death (√)',
        'Other treatment provided (√)',
        'If other service provided write the code',
        'Remarks/ Linkage to services etc',
        'Name & Signature of service provider',
      ],
      // Delivery Register
      'd2e27505-2ae5-4846-bddd-c8b0d015081f': [
        'S.N',
        'MRN',
        'Name of the mother',
        'Age',
        'Kebele',
        'Delivery date and time (DD/MM/YY - 00:00)',
        'Partograph Used (Y/N)',
        'SVD (√)',
        'Caesarean section (C/S) (√)',
        'Forceps / Vacuum Assisted (√)',
        'Episiotomy (√)',
        'Other procedures (√)',
        'Uterotonic Drugs Given (Write code)',
        'Controlled cord traction (CCT)',
        'Stable (√)',
        'Unstable / deteriorated and referred (√)',
        'Died (mother) (√)',
        'Cause of Death (Write Code)',
        'Pre-eclampsia (√)',
        'Eclampsia (√)',
        'APH (√)',
        'PPH (√)',
        'Other Obstetric Complications (√)',
        'Referred (√)',
        'Alive (√)',
        "APGAR Score 1' / 5'",
        'Sex (M/F)',
        'Weight in grams',
        'Still birth (1= Fresh, 2= Macerated)',
        'Live birth, died after arrival/delivery (√)',
        "MRN (Newborn's)",
        'Vitamin K (√)',
        'TTC eye ointment (√)',
        'Chlorhexidine cord care (√)',
        'Vaccinated at birth for (Write code)',
        'HIV Testing accepted (√)',
        'HIV re-testing accepted (√)',
        'HIV Test results (P/N)',
        'Known HIV positives (linked from ART) (√)',
        'Target population Category write code',
        'HIV positive delivery link to PMTCT',
        'Counseled on feeding options (√)',
        "Mother's ART Regimin (write the code)",
        'New born AZT + NVP (for 6 wks/12 wks)',
        'Partner HIV Testing accepted (√)',
        'Partner HIV Test results (P/N)',
        'HIV positives Partner linked to ART (√)',
        'Target population Category (partner)',
        'New acceptor (√)',
        'Repeat acceptor (√)',
        'IPPFP methods received (0-48hrs)',
        'Prematurity (√)',
        'Sepsis/ VSD (√)',
        'Respiratory distress/asphyxia (√)',
        'Low birth Weight (√)',
        'Congenital Malformation (√)',
        'Other (Write Code)',
        'Breast feeding initiated time (write code)',
        'Oxygen/ Resuscitation (√)',
        'Resuscitated and survived (√)',
        'Died (newborn) (√)',
        'Age at death (postnatal age)',
        'Cause of death (newborn)',
        'If alive, Birth notification given for mother (√)',
        'Managed by',
        'Remark',
      ],
    },
  },
  hiddenDatasets: {
    _type: Type.Array,
    _elements: { _type: Type.String },
    _description: 'Dataset names that feed an Excel template only and should be hidden from the on-screen table.',
    _default: ['immRegisterExcel', 'ancRegisterExcel', 'abortionRegisterExcel', 'deliveryRegisterExcel'],
  },
};

export interface EthiopiaReportsConfig {
  columnOrderByUuid: Record<string, Array<string>>;
  hiddenDatasets: Array<string>;
}
